import { FactValidationError } from "@invaro/opentax-core";
import { matchOccupation } from "@invaro/opentax-corpus-us-federal";

/**
 * THE single source of truth for inline eval flags <-> corpus fact ids.
 * Option registration (index.ts), fact assembly (eval.ts), and error hints
 * (output.ts) all derive from this table — it cannot drift in one place only.
 * A contract test asserts every corpus fact has an entry.
 */

export interface FactFlag {
  /** Corpus fact id this flag sets. */
  factId: string;
  /** Commander option declaration, e.g. "--wages <dollars>". */
  option: string;
  /** Commander's camelCased property name for this option. */
  key: string;
  /** Help text for --help. */
  help: string;
  /** true = presence flag (sets the fact to a boolean); false = takes a value. */
  boolean: boolean;
  /** For presence flags: the boolean the flag sets (default true). */
  setValue?: boolean;
  /** Help group heading (defaults to "Common situations:"). */
  group?: string;
}

/** Plain-English filing-status aliases -> canonical corpus values. */
const STATUS_ALIASES: Record<string, string> = {
  single: "single",
  mfj: "mfj",
  married: "mfj",
  marriedjoint: "mfj",
  marriedfilingjointly: "mfj",
  joint: "mfj",
  mfs: "mfs",
  marriedseparate: "mfs",
  marriedseparately: "mfs",
  marriedfilingseparately: "mfs",
  separate: "mfs",
  hoh: "hoh",
  headofhousehold: "hoh",
  qss: "qss",
  survivingspouse: "qss",
  qualifyingsurvivingspouse: "qss",
  widow: "qss",
  widower: "qss",
};

/** "Married Filing Jointly" / "head-of-household" / "mfj" all normalize. */
export function normalizeStatus(raw: string): string {
  const key = raw.toLowerCase().replace(/[^a-z]/g, "");
  return STATUS_ALIASES[key] ?? raw;
}

export const FACT_FLAGS: FactFlag[] = [
  {
    factId: "filingStatus",
    option: "--status <status>",
    key: "status",
    group: "Filing & family:",
    help: "single | married (mfj) | married-separate (mfs) | head-of-household (hoh) | surviving-spouse (qss)",
    boolean: false,
  },
  {
    factId: "wages",
    option: "--wages <dollars>",
    key: "wages",
    group: "Income:",
    help: 'wages in dollars, e.g. 50000 or "1234.56"',
    boolean: false,
  },
  {
    factId: "taxableInterest",
    option: "--interest <dollars>",
    key: "interest",
    group: "Income:",
    help: "taxable interest in dollars",
    boolean: false,
  },
  {
    factId: "qualifyingChildren",
    option: "--kids <n>",
    key: "kids",
    group: "Filing & family:",
    help: "qualifying children under 17 (CTC)",
    boolean: false,
  },
  {
    factId: "otherDependents",
    option: "--other-dependents <n>",
    key: "otherDependents",
    group: "Filing & family:",
    help: "dependents other than CTC children ($500 ODC, § 24(h)(4))",
    boolean: false,
  },
  {
    factId: "dependentCareExpenses",
    option: "--care-expenses <dollars>",
    key: "careExpenses",
    group: "Filing & family:",
    help: "employment-related dependent care expenses (§ 21, net of FSA)",
    boolean: false,
  },
  {
    factId: "careQualifyingIndividuals",
    option: "--care-persons <n>",
    key: "carePersons",
    group: "Filing & family:",
    help: "care-credit qualifying individuals (under-13 dependents etc.)",
    boolean: false,
  },
  {
    factId: "secondaryEarnedIncome",
    option: "--spouse-earned <dollars>",
    key: "spouseEarned",
    group: "Filing & family:",
    help: "lower-earning spouse's earned income (§ 21(d) joint limit)",
    boolean: false,
  },
  {
    factId: "saversContributions",
    option: "--savers-contributions <dollars>",
    key: "saversContributions",
    group: "Deductions & credits:",
    help: "taxpayer retirement contributions for the § 25B saver's credit",
    boolean: false,
  },
  {
    factId: "saversContributionsSpouse",
    option: "--savers-contributions-spouse <dollars>",
    key: "saversContributionsSpouse",
    group: "Deductions & credits:",
    help: "spouse retirement contributions for the § 25B saver's credit",
    boolean: false,
  },
  {
    factId: "isFullTimeStudent",
    option: "--student",
    key: "student",
    group: "Filing & family:",
    help: "taxpayer is a full-time student (denies § 25B)",
    boolean: true,
  },
  {
    factId: "spouseIsFullTimeStudent",
    option: "--spouse-student",
    key: "spouseStudent",
    group: "Filing & family:",
    help: "spouse is a full-time student (denies spouse's § 25B)",
    boolean: true,
  },
  {
    factId: "qualifiedAdoptionExpenses",
    option: "--adoption-expenses <dollars>",
    key: "adoptionExpenses",
    group: "Deductions & credits:",
    help: "qualified adoption expenses (§ 23; up to $5,000/$5,120 refundable)",
    boolean: false,
  },
  {
    factId: "adoptionIsSpecialNeeds",
    option: "--adoption-special-needs",
    key: "adoptionSpecialNeeds",
    group: "Deductions & credits:",
    help: "special-needs adoption finalized this year (deemed max credit)",
    boolean: true,
  },
  {
    factId: "taxExemptInterest",
    option: "--tax-exempt-interest <dollars>",
    key: "taxExemptInterest",
    group: "Income:",
    help: "tax-exempt interest (counts in § 86 and § 36B MAGI)",
    boolean: false,
  },
  {
    factId: "slcspAnnualPremium",
    option: "--slcsp <dollars>",
    key: "slcsp",
    group: "Health coverage (§ 36B):",
    help: "annual SLCSP benchmark premium (Form 1095-A line 33B)",
    boolean: false,
  },
  {
    factId: "marketplacePremiumsPaid",
    option: "--marketplace-premiums <dollars>",
    key: "marketplacePremiums",
    group: "Health coverage (§ 36B):",
    help: "annual Marketplace plan premiums (Form 1095-A line 33A)",
    boolean: false,
  },
  {
    factId: "advancePTC",
    option: "--aptc <dollars>",
    key: "aptc",
    group: "Health coverage (§ 36B):",
    help: "advance premium tax credit received (Form 1095-A line 33C)",
    boolean: false,
  },
  {
    factId: "ptcHouseholdSize",
    option: "--household-size <n>",
    key: "householdSize",
    group: "Health coverage (§ 36B):",
    help: "tax family size for the poverty-line lookup (§ 36B(d)(1))",
    boolean: false,
  },
  {
    factId: "foreignEarnedIncome",
    option: "--foreign-earned <dollars>",
    key: "foreignEarned",
    group: "Income:",
    help: "§ 911-qualified foreign earned income (also include in wages/SE)",
    boolean: false,
  },
  {
    factId: "fiduciaryType",
    option: "--fiduciary <type>",
    key: "fiduciary",
    group: "Estates & trusts (Form 1041):",
    help: "estate | simple-trust | complex-trust (§ 642(b) exemption)",
    boolean: false,
  },
  {
    factId: "fiduciaryIncomeBeforeExemption",
    option: "--fiduciary-income <dollars>",
    key: "fiduciaryIncome",
    group: "Estates & trusts (Form 1041):",
    help: "1041 taxable income before the exemption, after distributions",
    boolean: false,
  },
  {
    factId: "fiduciaryLongTermGains",
    option: "--fiduciary-gains <dollars>",
    key: "fiduciaryGains",
    group: "Estates & trusts (Form 1041):",
    help: "retained trust/estate capital gains (refuses if positive)",
    boolean: false,
  },
  {
    factId: "householdEmployeeCashWages",
    option: "--household-wages <dollars>",
    key: "householdWages",
    group: "Business owner:",
    help: "cash wages to one household employee (Schedule H)",
    boolean: false,
  },
  {
    factId: "householdFutaTestMet",
    option: "--household-futa",
    key: "householdFuta",
    group: "Business owner:",
    help: "$1,000+/quarter household wages — FUTA applies (attested)",
    boolean: true,
  },
  {
    factId: "isFarmerOrFisherman",
    option: "--farmer",
    key: "farmer",
    group: "Business owner:",
    help: "⅔ of gross income from farming/fishing (§ 6654(i) safe harbor)",
    boolean: true,
  },
  {
    factId: "homeOfficeSquareFeet",
    option: "--home-office-sqft <n>",
    key: "homeOfficeSqft",
    group: "Business owner:",
    help: "home office square feet (simplified method target)",
    boolean: false,
  },
  {
    factId: "corpIsREITorRIC",
    option: "--corp-reit-ric",
    key: "corpReitRic",
    group: "Corporate & entity (Form 1120):",
    help: "corporation is a REIT/RIC (refuses — §§ 857/852)",
    boolean: true,
  },
  {
    factId: "isAge65OrOlder",
    option: "--age65",
    key: "age65",
    group: "Filing & family:",
    help: "taxpayer is 65 or older",
    boolean: true,
  },
  {
    factId: "isBlind",
    option: "--blind",
    key: "blind",
    group: "Filing & family:",
    help: "taxpayer is blind",
    boolean: true,
  },
  {
    factId: "spouseIsAge65OrOlder",
    option: "--spouse-age65",
    key: "spouseAge65",
    group: "Filing & family:",
    help: "spouse is 65 or older (mfj)",
    boolean: true,
  },
  {
    factId: "spouseIsBlind",
    option: "--spouse-blind",
    key: "spouseBlind",
    group: "Filing & family:",
    help: "spouse is blind (mfj)",
    boolean: true,
  },
  {
    factId: "isClaimedAsDependent",
    option: "--dependent",
    key: "dependent",
    group: "Filing & family:",
    help: "taxpayer can be claimed as a dependent",
    boolean: true,
  },
  {
    factId: "qualifiedTips",
    option: "--tips <dollars>",
    key: "tips",
    group: "Income:",
    help: "qualified tips included in wages (§ 224)",
    boolean: false,
  },
  {
    factId: "qualifiedOvertimePremium",
    option: "--overtime <dollars>",
    key: "overtime",
    group: "Income:",
    help: "FLSA overtime premium included in wages (§ 225)",
    boolean: false,
  },
  {
    factId: "longTermCapitalGains",
    option: "--gains <dollars>",
    key: "gains",
    group: "Income:",
    help: "long-term capital gains + qualified dividends",
    boolean: false,
  },
  {
    factId: "qualifiedDividends",
    option: "--qualified-dividends <dollars>",
    key: "qualifiedDividends",
    group: "Income:",
    help: "qualified dividends (§ 1(h)(11)); use this standalone when a net capital loss also exists",
    boolean: false,
  },
  {
    factId: "shortTermCapitalGains",
    option: "--short-term-gains <dollars>",
    key: "shortTermGains",
    group: "Income:",
    help: "net short-term capital gain (§ 1222(5)), ordinary rates; mutually exclusive with netCapitalLoss",
    boolean: false,
  },
  {
    factId: "ordinaryDividends",
    option: "--ordinary-dividends <dollars>",
    key: "ordinaryDividends",
    group: "Income:",
    help: "non-qualified dividends (1099-DIV box 1a minus box 1b), ordinary rates",
    boolean: false,
  },
  {
    factId: "netCapitalLoss",
    option: "--capital-loss <dollars>",
    key: "capitalLoss",
    group: "Income:",
    help: "OVERALL net capital loss from Schedule D, positive (§ 1211(b)); for mixed years use the per-bucket loss flags instead",
    boolean: false,
  },
  {
    factId: "shortTermCapitalLoss",
    option: "--short-term-loss <dollars>",
    key: "shortTermLoss",
    group: "Income:",
    help: "net short-term capital LOSS (Schedule D line 7 as a loss, positive); nets against --long-term-gains per § 1222(11)",
    boolean: false,
  },
  {
    factId: "longTermCapitalLoss",
    option: "--long-term-loss <dollars>",
    key: "longTermLoss",
    group: "Income:",
    help: "net long-term capital LOSS (Schedule D line 15 as a loss, positive); nets against --short-term-gains per § 1222(9)",
    boolean: false,
  },
  {
    factId: "pensionGrossPayments",
    option: "--pension-gross <dollars>",
    key: "pensionGross",
    group: "Retirement:",
    help: "gross annuity payments this year (1099-R box 1); the § 72(d) Simplified Method computes the taxable part",
    boolean: false,
  },
  {
    factId: "pensionCostBasis",
    option: "--pension-basis <dollars>",
    key: "pensionBasis",
    group: "Retirement:",
    help: "after-tax investment in the contract at the annuity starting date (1099-R box 9b)",
    boolean: false,
  },
  {
    factId: "pensionAgeAtStart",
    option: "--pension-age-at-start <age>",
    key: "pensionAgeAtStart",
    group: "Retirement:",
    help: "age at the ANNUITY STARTING DATE (single-life § 72(d) table: ≤55:360 ≤60:310 ≤65:260 ≤70:210 71+:160)",
    boolean: false,
  },
  {
    factId: "pensionIsJointAndSurvivor",
    option: "--pension-joint",
    key: "pensionJoint",
    group: "Retirement:",
    help: "joint-and-survivor annuity (post-1997 start): the combined-ages table applies",
    boolean: true,
  },
  {
    factId: "pensionCombinedAgesAtStart",
    option: "--pension-combined-ages <n>",
    key: "pensionCombinedAges",
    group: "Retirement:",
    help: "combined ages at the starting date for --pension-joint (≤110:410 ≤120:360 ≤130:310 ≤140:260 141+:210)",
    boolean: false,
  },
  {
    factId: "pensionMonthsThisYear",
    option: "--pension-months <1-12>",
    key: "pensionMonths",
    group: "Retirement:",
    help: "monthly payments received this year (default 12)",
    boolean: false,
  },
  {
    factId: "pensionBasisPreviouslyRecovered",
    option: "--pension-basis-recovered <dollars>",
    key: "pensionBasisRecovered",
    group: "Retirement:",
    help: "basis recovered tax-free in prior years (lifetime recovery caps at the cost basis)",
    boolean: false,
  },
  {
    factId: "rentalIncomeBeforeDepreciation",
    option: "--rental-income-pre-depreciation <dollars>",
    key: "rentalIncomePreDepreciation",
    group: "Income:",
    help: "Schedule E rental result BEFORE depreciation (rents minus cash expenses); the engine subtracts § 168 depreciation",
    boolean: false,
  },
  {
    factId: "rentalDepreciableBasis",
    option: "--rental-basis <dollars>",
    key: "rentalBasis",
    group: "Income:",
    help: "depreciable basis of the rental BUILDING (excluding land) — § 168 GDS 27.5-yr straight line, mid-month",
    boolean: false,
  },
  {
    factId: "rentalPlacedInServiceMonth",
    option: "--rental-in-service-month <1-12>",
    key: "rentalInServiceMonth",
    group: "Income:",
    help: "month placed in service THIS year (Pub 946 Table A-6 first-year row); omit for property in service all year (3.636%)",
    boolean: false,
  },
  {
    factId: "selfEmploymentNetProfit",
    option: "--se-profit <dollars>",
    key: "seProfit",
    group: "Income:",
    help: "self-employment net profit (Schedule C)",
    boolean: false,
  },
  {
    factId: "scheduleCNetLoss",
    option: "--schedule-c-loss <dollars>",
    key: "scheduleCLoss",
    group: "Income:",
    help: "Schedule C/F net loss as a positive number (reduces gross and earned income; no SE tax)",
    boolean: false,
  },
  {
    factId: "qbiW2Wages",
    option: "--qbi-w2-wages <dollars>",
    key: "qbiW2Wages",
    group: "Business owner:",
    help: "W-2 wages paid by the business (§ 199A above-threshold wage limit)",
    boolean: false,
  },
  {
    factId: "qbiUBIA",
    option: "--qbi-ubia <dollars>",
    key: "qbiUbia",
    group: "Business owner:",
    help: "UBIA of the business's qualified property (§ 199A 2.5% prong)",
    boolean: false,
  },
  {
    factId: "businessIsSSTB",
    option: "--qbi-sstb",
    key: "qbiSstb",
    group: "Business owner:",
    help: "the business is a specified service trade or business (§ 199A(d)(2))",
    boolean: true,
  },
  {
    factId: "businessIsSSTB",
    option: "--qbi-not-sstb",
    key: "qbiNotSstb",
    group: "Business owner:",
    help: "the business is NOT an SSTB",
    boolean: true,
    setValue: false,
  },
  {
    factId: "sepContribution",
    option: "--sep <dollars>",
    key: "sep",
    group: "Deductions & savings:",
    help: "self-employed SEP/solo-401(k) employer contribution (§ 404(h))",
    boolean: false,
  },
  {
    factId: "selfEmployedHealthPremiums",
    option: "--se-health <dollars>",
    key: "seHealth",
    group: "Deductions & savings:",
    help: "self-employed health insurance premiums (§ 162(l))",
    boolean: false,
  },
  {
    factId: "employeeAnnualWages",
    option: "--employee-wages <dollars>",
    key: "employeeWages",
    group: "Business owner:",
    help: "one employee's annual wages (employer payroll-tax target)",
    boolean: false,
  },
  {
    factId: "qreCurrentYear",
    option: "--qre <dollars>",
    key: "qre",
    group: "Business owner:",
    help: "qualified research expenses this year (§ 41 ASC target)",
    boolean: false,
  },
  {
    factId: "qreAvgPrior3Years",
    option: "--qre-prior-avg <dollars>",
    key: "qrePriorAvg",
    group: "Business owner:",
    help: "average QREs of the 3 prior years (0 = the 6% startup rate)",
    boolean: false,
  },
  {
    factId: "k1OrdinaryBusinessIncome",
    option: "--k1 <dollars>",
    key: "k1",
    group: "Income:",
    help: "K-1 box 1 pass-through business income (S-corp/partnership; QBI-eligible, not SE-taxed)",
    boolean: false,
  },
  {
    factId: "hsaContribution",
    option: "--hsa <dollars>",
    key: "hsa",
    group: "Deductions & savings:",
    help: "personal HSA contributions (§ 223)",
    boolean: false,
  },
  {
    factId: "hsaCoverage",
    option: "--hsa-coverage <type>",
    key: "hsaCoverage",
    group: "Deductions & savings:",
    help: "HDHP coverage: self | family",
    boolean: false,
  },
  {
    factId: "isAge55OrOlder",
    option: "--age55",
    key: "age55",
    group: "Deductions & savings:",
    help: "taxpayer is 55+ (HSA catch-up)",
    boolean: true,
  },
  {
    factId: "studentLoanInterest",
    option: "--student-loan <dollars>",
    key: "studentLoan",
    group: "Deductions & savings:",
    help: "student loan interest paid (§ 221)",
    boolean: false,
  },
  {
    factId: "carLoanInterest",
    option: "--car-loan <dollars>",
    key: "carLoan",
    group: "Deductions & savings:",
    help: "qualified vehicle loan interest paid (§ 163(h)(4))",
    boolean: false,
  },
  {
    factId: "charitableCashContributions",
    option: "--charity <dollars>",
    key: "charity",
    group: "Deductions & savings:",
    help: "cash charitable contributions (§ 170(p) non-itemizer, or Schedule A when itemizing)",
    boolean: false,
  },
  {
    factId: "stateAndLocalTaxesPaid",
    option: "--salt <dollars>",
    key: "salt",
    group: "Deductions & savings:",
    help: "state and local income/sales + property taxes paid (§ 164, OBBBA cap)",
    boolean: false,
  },
  {
    factId: "forceItemized",
    option: "--force-itemized",
    key: "forceItemized",
    group: "Deductions & savings:",
    help: "honor an explicit § 63(e) election to itemize even when the standard deduction is larger",
    boolean: true,
    setValue: true,
  },
  {
    factId: "casualtyFederalDisasterLosses",
    option: "--casualty-disaster <dollars>",
    key: "casualtyDisaster",
    group: "Deductions & savings:",
    help: "federally-declared-disaster casualty losses after per-event $100 floors (§ 165(h); 10% AGI floor applied by the engine)",
    boolean: false,
  },
  {
    factId: "casualtyQualifiedDisasterLosses",
    option: "--casualty-qualified <dollars>",
    key: "casualtyQualified",
    group: "Deductions & savings:",
    help: "net QUALIFIED disaster losses after per-event $500 floors (no AGI floor; adds to the standard deduction when not itemizing)",
    boolean: false,
  },
  {
    factId: "socialSecurityWages",
    option: "--ss-wages <dollars>",
    key: "ssWages",
    group: "Income:",
    help: "W-2 box 3 social security wages (Schedule SE line 8a coordination; defaults to box-1 wages)",
    boolean: false,
  },
  {
    factId: "medicareWages",
    option: "--medicare-wages <dollars>",
    key: "medicareWages",
    group: "Income:",
    help: "W-2 box 5 Medicare wages (Form 8959 base; defaults to box-1 wages)",
    boolean: false,
  },
  {
    factId: "scheduleENetIncome",
    option: "--schedule-e <dollars>",
    key: "scheduleE",
    group: "Income:",
    help: "net Schedule E rental/royalty income after § 469, non-QBI (QBI-eligible goes in --k1)",
    boolean: false,
  },
  {
    factId: "passiveActivityIncome",
    option: "--passive-income <dollars>",
    key: "passiveIncome",
    group: "Income:",
    help: "net passive-activity income (absorbs passive losses; target us.federal.passive_loss_allowed)",
    boolean: false,
  },
  {
    factId: "selfRentalNetIncome",
    option: "--self-rental-income <dollars>",
    key: "selfRentalIncome",
    group: "Income:",
    help: "self-rental subset of --passive-income, nonpassive per Reg. 1.469-2(f)(6) (cannot absorb losses)",
    boolean: false,
  },
  {
    factId: "passiveActivityLosses",
    option: "--passive-losses <dollars>",
    key: "passiveLosses",
    group: "Income:",
    help: "total passive-activity losses incl. carryovers, positive number (§ 469 / Form 8582)",
    boolean: false,
  },
  {
    factId: "rentalActiveParticipationLosses",
    option: "--rental-active-losses <dollars>",
    key: "rentalActiveLosses",
    group: "Income:",
    help: "portion of passive losses from active-participation rental real estate (§ 469(i) allowance)",
    boolean: false,
  },
  {
    factId: "mfsLivedApartAllYear",
    option: "--mfs-lived-apart",
    key: "mfsLivedApart",
    group: "Filing & family:",
    help: "MFS filer lived apart from spouse at ALL times (§ 469(i)(5): $12,500 allowance instead of $0)",
    boolean: true,
    setValue: true,
  },
  {
    factId: "isRetiredOnTotalDisability",
    option: "--retired-disabled",
    key: "retiredDisabled",
    group: "Filing & family:",
    help: "retired on permanent/total disability with physician's statement (Schedule R, § 22(b))",
    boolean: true,
    setValue: true,
  },
  {
    factId: "scheduleRDisabilityIncome",
    option: "--disability-income <dollars>",
    key: "disabilityIncome",
    group: "Income:",
    help: "§§ 72/105(a) taxable disability income (caps the under-65 Schedule R initial amount)",
    boolean: false,
  },
  {
    factId: "nontaxableBenefitsForScheduleR",
    option: "--schr-nontaxable <dollars>",
    key: "schrNontaxable",
    group: "Income:",
    help: "nontaxable SS/RRB/VA benefits reducing the § 22 amount (Schedule R)",
    boolean: false,
  },
  {
    factId: "qbiLossOffset",
    option: "--qbi-loss-offset <dollars>",
    key: "qbiLossOffset",
    group: "Business owner:",
    help: "QBI-eligible losses outside --se-profit/--k1 (e.g. nonpassive rental loss) reducing the § 199A base",
    boolean: false,
  },
  {
    factId: "nonpassiveScheduleELoss",
    option: "--schedule-e-loss <dollars>",
    key: "scheduleELoss",
    group: "Income:",
    help: "nonpassive Schedule E loss (§ 469(c)(7) RE professional), positive number",
    boolean: false,
  },
  {
    factId: "stateTaxableIncome",
    option: "--state-taxable <dollars>",
    key: "stateTaxable",
    group: "Income:",
    help: "state taxable income for the state tax targets (us.ca/us.va/us.il/us.ny income_tax)",
    boolean: false,
  },
  {
    factId: "paCompensationAdjustment",
    option: "--pa-comp-adjustment <dollars>",
    key: "paCompAdjustment",
    group: "Income:",
    help: "PA W-2 Box 16 minus Box 1 (401(k) deferrals are PA-taxable; may be negative; also taxable cost-recovery early distributions) (us.pa.taxable_income)",
    boolean: false,
  },
  {
    factId: "paUnreimbursedBusinessExpenses",
    option: "--pa-ue-expenses <dollars>",
    key: "paUeExpenses",
    group: "Income:",
    help: "PA Schedule UE unreimbursed employee business expenses (PA-40 line 1b)",
    boolean: false,
  },
  {
    factId: "paInterestIncome",
    option: "--pa-interest <dollars>",
    key: "paInterest",
    group: "Income:",
    help: "PA-taxable interest (PA-40 line 2, gross class — includes commercial-annuity interest)",
    boolean: false,
  },
  {
    factId: "paDividendIncome",
    option: "--pa-dividends <dollars>",
    key: "paDividends",
    group: "Income:",
    help: "PA-taxable dividends incl. mutual-fund capital-gain distributions (PA-40 line 3)",
    boolean: false,
  },
  {
    factId: "paBusinessNetIncome",
    option: "--pa-business-net <dollars>",
    key: "paBusinessNet",
    group: "Income:",
    help: "taxpayer's own PA business/profession/farm net income or loss (PA-40 line 4; loss never crosses classes or spouses)",
    boolean: false,
  },
  {
    factId: "paSpouseBusinessNetIncome",
    option: "--pa-spouse-business-net <dollars>",
    key: "paSpouseBusinessNet",
    group: "Income:",
    help: "spouse's own PA business net income or loss (PA-40 line 4)",
    boolean: false,
  },
  {
    factId: "paPropertyGainNet",
    option: "--pa-property-gain <dollars>",
    key: "paPropertyGain",
    group: "Income:",
    help: "taxpayer's own PA net gain/loss from disposition of property (PA-40 line 5; no carryover)",
    boolean: false,
  },
  {
    factId: "paSpousePropertyGainNet",
    option: "--pa-spouse-property-gain <dollars>",
    key: "paSpousePropertyGain",
    group: "Income:",
    help: "spouse's own PA net gain/loss from disposition of property (PA-40 line 5)",
    boolean: false,
  },
  {
    factId: "paRentRoyaltyNet",
    option: "--pa-rent-royalty <dollars>",
    key: "paRentRoyalty",
    group: "Income:",
    help: "taxpayer's own PA net rents/royalties/patents/copyrights (PA-40 line 6; <30-day rentals are business)",
    boolean: false,
  },
  {
    factId: "paSpouseRentRoyaltyNet",
    option: "--pa-spouse-rent-royalty <dollars>",
    key: "paSpouseRentRoyalty",
    group: "Income:",
    help: "spouse's own PA net rents/royalties/patents/copyrights (PA-40 line 6)",
    boolean: false,
  },
  {
    factId: "paEstateTrustIncome",
    option: "--pa-estate-trust <dollars>",
    key: "paEstateTrust",
    group: "Income:",
    help: "PA estate/trust income (PA-40 line 7, Schedule J; never negative)",
    boolean: false,
  },
  {
    factId: "paGamblingWinnings",
    option: "--pa-gambling <dollars>",
    key: "paGambling",
    group: "Income:",
    help: "PA gambling and lottery winnings net of wager costs (PA-40 line 8; noncash PA Lottery prizes exempt)",
    boolean: false,
  },
  {
    factId: "pa529Contributions",
    option: "--pa-529 <dollars>",
    key: "pa529",
    group: "Adjustments:",
    help: "PA Schedule O 529 deduction, caller-capped at $19,000 per beneficiary per taxpayer-spouse (2025)",
    boolean: false,
  },
  {
    factId: "paAbleContributions",
    option: "--pa-able <dollars>",
    key: "paAble",
    group: "Adjustments:",
    help: "PA Schedule O ABLE deduction, capped at the federal gift-tax exclusion ($19,000 in 2025)",
    boolean: false,
  },
  {
    factId: "paMsaHsaContributions",
    option: "--pa-msa-hsa <dollars>",
    key: "paMsaHsa",
    group: "Adjustments:",
    help: "PA Schedule O MSA + HSA deduction (federal-allowed amounts)",
    boolean: false,
  },
  {
    factId: "paSpDependentChildren",
    option: "--pa-sp-dependents <count>",
    key: "paSpDependents",
    group: "Credits:",
    help: "PA Schedule SP dependent children count (+$9,500 each on the Tax Forgiveness threshold) (us.pa.tax_forgiveness)",
    boolean: false,
  },
  {
    factId: "paEligibilityIncomeAddbacks",
    option: "--pa-eligibility-addbacks <dollars>",
    key: "paEligibilityAddbacks",
    group: "Credits:",
    help: "PA Schedule SP nontaxable eligibility-income add-backs (gifts, inheritances, non-PA income, ...) (us.pa.tax_forgiveness)",
    boolean: false,
  },
  {
    factId: "paResidentCredit",
    option: "--pa-resident-credit <dollars>",
    key: "paResidentCredit",
    group: "Credits:",
    help: "PA resident credit for tax paid other states (PA-40 line 22; subtracts before Tax Forgiveness)",
    boolean: false,
  },
  {
    factId: "mfsAbuseOrAbandonmentException",
    option: "--mfs-abuse-abandonment-relief",
    key: "mfsAbuseAbandonmentRelief",
    group: "Health coverage (§ 36B):",
    help: "Reg. 1.36B-2(b)(2) abuse/abandonment relief (MFS can claim PTC)",
    boolean: true,
  },
  {
    factId: "hsaDistributions",
    option: "--hsa-distributions <dollars>",
    key: "hsaDistributions",
    group: "Common situations:",
    help: "HSA distributions received (1099-SA box 1)",
    boolean: false,
  },
  {
    factId: "hsaQualifiedMedicalExpenses",
    option: "--hsa-medical <dollars>",
    key: "hsaMedical",
    group: "Common situations:",
    help: "qualified medical expenses paid from HSA distributions",
    boolean: false,
  },
  {
    factId: "hsaDistributionPenaltyExempt",
    option: "--hsa-penalty-exempt",
    key: "hsaPenaltyExempt",
    group: "Common situations:",
    help: "65+/death/disability exception to the 20% HSA additional tax",
    boolean: true,
  },
  {
    factId: "mfsConsideredUnmarried",
    option: "--mfs-considered-unmarried",
    key: "mfsConsideredUnmarried",
    group: "Filing & family:",
    help: "MFS filer meets the 32(d)(2) separation tests (unlocks EITC)",
    boolean: true,
  },
  {
    factId: "spouseEducatorExpenses",
    option: "--spouse-educator-expenses <dollars>",
    key: "spouseEducatorExpenses",
    group: "Deductions & credits:",
    help: "spouse's eligible educator expenses (separate $300 cap)",
    boolean: false,
  },
  {
    factId: "alimonyPaidPre2019",
    option: "--alimony-paid-pre2019 <dollars>",
    key: "alimonyPaidPre2019",
    group: "Deductions & credits:",
    help: "alimony paid under a pre-2019 instrument (deductible)",
    boolean: false,
  },
  {
    factId: "alimonyReceivedPre2019",
    option: "--alimony-received-pre2019 <dollars>",
    key: "alimonyReceivedPre2019",
    group: "Income:",
    help: "alimony received under a pre-2019 instrument (taxable)",
    boolean: false,
  },
  {
    factId: "federalEstimatedPayments",
    option: "--estimated-payments <dollars>",
    key: "estimatedPayments",
    group: "Common situations:",
    help: "federal estimated payments + prior-year overpayment applied (line 26)",
    boolean: false,
  },
  {
    factId: "federalExtensionPayment",
    option: "--extension-payment <dollars>",
    key: "extensionPayment",
    group: "Common situations:",
    help: "payment made with Form 4868 extension (line 31)",
    boolean: false,
  },
  {
    factId: "hasChildUnderSix",
    option: "--child-under-six",
    key: "childUnderSix",
    group: "Income:",
    help: "at least one qualifying child under age 6 at year end (CA Young Child Tax Credit)",
    boolean: true,
  },
  {
    factId: "caRentedPrincipalResidence",
    option: "--ca-renter",
    key: "caRenter",
    group: "Income:",
    help: "rented a CA principal residence for at least half the year, not a dependent, property not tax-exempt (CA renter's credit)",
    boolean: true,
  },
  {
    factId: "caAmti",
    option: "--ca-amti <dollars>",
    key: "caAmti",
    group: "Income:",
    help: "CA alternative minimum taxable income, agent-composed per R&TC §§ 17062(c)-(e)/17062.1 (us.ca.amt)",
    boolean: false,
  },
  {
    factId: "caRegularTax",
    option: "--ca-regular-tax <dollars>",
    key: "caRegularTax",
    group: "Income:",
    help: "CA 'regular tax' (Form 540 line 31 net of exemption credits) for the Schedule P TMT comparison (us.ca.amt)",
    boolean: false,
  },
  {
    factId: "nyYonkersBase",
    option: "--ny-yonkers-base <dollars>",
    key: "nyYonkersBase",
    group: "Income:",
    help: "NY Yonkers surcharge base (IT-201-I Yonkers worksheet line m = line 46 minus the ESCC/IT-214/IT-216/EIC/IT-209/IT-272/69-69a/ATT-13 credit bundle) for us.ny.yonkers_surcharge (16.75%, IT-201 line 55)",
    boolean: false,
  },
  {
    factId: "nyIt214Fagi",
    option: "--ny-it214-fagi <dollars>",
    key: "nyIt214Fagi",
    group: "Income:",
    help: "federal AGI for the NY IT-214 Real Property Tax Credit (Form IT-214 line 8); over $18,000 disqualifies (us.ny.it214)",
    boolean: false,
  },
  {
    factId: "nyIt214Eligible",
    option: "--ny-it214-eligible",
    key: "nyIt214Eligible",
    group: "Income:",
    help: "attests the NY IT-214 non-income eligibility gates: 6+ month residency, not a dependent, assessed value <= $85,000, average monthly adjusted rent <= $450 (us.ny.it214)",
    boolean: true,
  },
  {
    factId: "nyIt214TotalRent",
    option: "--ny-it214-total-rent <dollars>",
    key: "nyIt214TotalRent",
    group: "Income:",
    help: "IT-214 line 11 total rent paid (excluding subsidized portions); the engine applies the printed line-12 percentage menu and $450 monthly cap (us.ny.it214)",
    boolean: false,
  },
  {
    factId: "nyIt214RentPercent",
    option: "--ny-it214-rent-percent <pct>",
    key: "nyIt214RentPercent",
    group: "Income:",
    help: "IT-214 line 12 printed percentage menu: 50 (heat+gas+electricity+furnishings+board), 75 (+furnishings), 80 (heat+gas+electricity), 85 (heat or heat+gas), 100 (none)",
    boolean: false,
  },
  {
    factId: "nyIt214MonthsPaid",
    option: "--ny-it214-months <n>",
    key: "nyIt214MonthsPaid",
    group: "Income:",
    help: "IT-214 line 13 divisor: months rent was paid during the year (us.ny.it214)",
    boolean: false,
  },
  {
    factId: "nyIt214HomeownerTaxes",
    option: "--ny-it214-homeowner-taxes <dollars>",
    key: "nyIt214HomeownerTaxes",
    group: "Income:",
    help: "IT-214 line 17: homeowners' real property taxes plus special assessments (us.ny.it214)",
    boolean: false,
  },
  {
    factId: "nyIt216StateCredit",
    option: "--ny-it216-state-credit <dollars>",
    key: "nyIt216StateCredit",
    group: "Income:",
    help: "NY State child and dependent care credit (Form IT-216 line 14) — Worksheet 2 line 1 starting amount for the NYC credit (us.ny.nyc_cdcc)",
    boolean: false,
  },
  {
    factId: "nyIt216Under4Expenses",
    option: "--ny-it216-under4-expenses <dollars>",
    key: "nyIt216Under4Expenses",
    group: "Income:",
    help: "IT-216 line 23 qualified care expenses for children under 4 — numerator of the NYC credit proration (us.ny.nyc_cdcc)",
    boolean: false,
  },
  {
    factId: "nyIt216TotalExpenses",
    option: "--ny-it216-total-expenses <dollars>",
    key: "nyIt216TotalExpenses",
    group: "Income:",
    help: "IT-216 line 3a total qualified care expenses — denominator of the NYC credit proration, capped at 100% (us.ny.nyc_cdcc)",
    boolean: false,
  },
  {
    factId: "businessMilesDriven",
    option: "--business-miles <n>",
    key: "businessMiles",
    group: "Business owner:",
    help: "business miles for the standard mileage rate (70¢ 2025 / 72.5¢ 2026; standalone target)",
    boolean: false,
  },
  {
    factId: "niitInvestmentExpenses",
    option: "--niit-expenses <dollars>",
    key: "niitExpenses",
    group: "Investor (AMT / QSBS):",
    help: "Form 8960 lines 9-10 deductions properly allocable to investment income (§ 1411(c)(1)(B))",
    boolean: false,
  },
  {
    factId: "investmentInterestDeduction",
    option: "--investment-interest <dollars>",
    key: "investmentInterest",
    group: "Deductions & savings:",
    help: "deductible investment interest (§ 163(d), post-Form-4952 limit attested)",
    boolean: false,
  },
  {
    factId: "gamblingLossesItemized",
    option: "--gambling-losses <dollars>",
    key: "gamblingLosses",
    group: "Deductions & savings:",
    help: "gambling losses (§ 165(d), Schedule A line 16) — already limited to winnings by the preparer; 100% for TY2025, OBBBA 90% haircut begins TY2026",
    boolean: false,
  },
  {
    factId: "otherItemizedDeductions",
    option: "--other-itemized <dollars>",
    key: "otherItemized",
    group: "Deductions & savings:",
    help: "Schedule A line 16 write-ins (impairment-related work expenses, estate tax on IRD, bond premium), attested total",
    boolean: false,
  },
  {
    factId: "noncashCharitableContributions",
    option: "--charity-noncash <dollars>",
    key: "charityNoncash",
    group: "Deductions & savings:",
    help: "noncash charitable contributions allowed this year (Form 8283; AGI limits attested)",
    boolean: false,
  },
  {
    factId: "otherOrdinaryIncome",
    option: "--other-income <dollars>",
    key: "otherIncome",
    group: "Income:",
    help: "Schedule 1 line 8 other income (gambling W-2G, prizes, Alaska PFD, jury duty)",
    boolean: false,
  },
  {
    factId: "eitcAdditionalQualifyingChildren",
    option: "--eitc-extra-children <n>",
    key: "eitcExtraChildren",
    group: "Filing & family:",
    help: "EIC-only qualifying children beyond the CTC count (under 19, students under 24, disabled any age)",
    boolean: false,
  },
  {
    factId: "mortgageInterestPaid",
    option: "--mortgage-interest <dollars>",
    key: "mortgageInterest",
    group: "Deductions & savings:",
    help: "home mortgage interest on acquisition debt (§ 163(h)(3))",
    boolean: false,
  },
  {
    factId: "mortgageAverageBalance",
    option: "--mortgage-balance <dollars>",
    key: "mortgageBalance",
    group: "Deductions & savings:",
    help: "average mortgage balance for the year ($750k limit proration)",
    boolean: false,
  },
  {
    factId: "medicalExpenses",
    option: "--medical <dollars>",
    key: "medical",
    group: "Deductions & savings:",
    help: "unreimbursed medical expenses (§ 213, over 7.5% of AGI)",
    boolean: false,
  },
  {
    factId: "educatorExpenses",
    option: "--educator-expenses <dollars>",
    key: "educatorExpenses",
    group: "Deductions & savings:",
    help: "eligible educator classroom expenses (§ 62(a)(2)(D); engine caps at $300/educator)",
    boolean: false,
  },
  {
    factId: "otherAdjustments",
    option: "--other-adjustments <dollars>",
    key: "otherAdjustments",
    group: "Deductions & savings:",
    help: "Schedule 1 lines 24a-z write-in adjustments (jury pay to employer, reforestation, SUB repayment, 501(c)(18)(D), discrimination/whistleblower attorney fees), attested total",
    boolean: false,
  },
  {
    factId: "earlyWithdrawalPenaltyPaid",
    option: "--early-withdrawal-penalty <dollars>",
    key: "earlyWithdrawalPenalty",
    group: "Deductions & savings:",
    help: "penalty on early withdrawal of savings (1099-INT box 2; § 62(a)(9))",
    boolean: false,
  },
  {
    factId: "iraContribution",
    option: "--ira <dollars>",
    key: "ira",
    group: "Deductions & savings:",
    help: "traditional IRA contributions (§ 219)",
    boolean: false,
  },
  {
    factId: "isActivePlanParticipant",
    option: "--covered-by-plan",
    key: "coveredByPlan",
    group: "Deductions & savings:",
    help: "covered by an employer retirement plan (W-2 box 13)",
    boolean: true,
  },
  {
    factId: "isActivePlanParticipant",
    option: "--not-covered-by-plan",
    key: "notCoveredByPlan",
    group: "Deductions & savings:",
    help: "NOT covered by an employer retirement plan",
    boolean: true,
    setValue: false,
  },
  {
    factId: "spouseIsActivePlanParticipant",
    option: "--spouse-covered-by-plan",
    key: "spouseCoveredByPlan",
    group: "Deductions & savings:",
    help: "spouse is covered by an employer retirement plan",
    boolean: true,
  },
  {
    factId: "spouseIsActivePlanParticipant",
    option: "--spouse-not-covered-by-plan",
    key: "spouseNotCoveredByPlan",
    group: "Deductions & savings:",
    help: "spouse is NOT covered by an employer retirement plan",
    boolean: true,
    setValue: false,
  },
  {
    factId: "isAge50OrOlder",
    option: "--age50",
    key: "age50",
    group: "Deductions & savings:",
    help: "taxpayer is 50+ (IRA catch-up)",
    boolean: true,
  },
  {
    factId: "aotcExpensesStudent1",
    option: "--aotc <dollars>",
    key: "aotc",
    group: "Education credits:",
    help: "qualified expenses, first AOTC student (§ 25A(b))",
    boolean: false,
  },
  {
    factId: "aotcExpensesStudent2",
    option: "--aotc2 <dollars>",
    key: "aotc2",
    group: "Education credits:",
    help: "qualified expenses, second AOTC student",
    boolean: false,
  },
  {
    factId: "aotcExpensesStudent3",
    option: "--aotc3 <dollars>",
    key: "aotc3",
    group: "Education credits:",
    help: "qualified expenses, third AOTC student",
    boolean: false,
  },
  {
    factId: "llcQualifiedExpenses",
    option: "--llc <dollars>",
    key: "llc",
    group: "Education credits:",
    help: "Lifetime Learning Credit expenses, per return (§ 25A(c))",
    boolean: false,
  },
  {
    factId: "isSubjectToKiddieTax",
    option: "--kiddie-tax-child",
    key: "kiddieTaxChild",
    group: "Filing & family:",
    help: "taxpayer is a § 1(g) kiddie-tax child (Form 8615 tax; no refundable AOTC)",
    boolean: true,
  },
  {
    factId: "parentTaxableIncome",
    option: "--parent-taxable-income <dollars>",
    key: "parentTaxableIncome",
    group: "Filing & family:",
    help: "the parent's taxable income (Form 8615 line 6)",
    boolean: false,
  },
  {
    factId: "parentFilingStatus",
    option: "--parent-status <status>",
    key: "parentStatus",
    group: "Filing & family:",
    help: "the parent's filing status (Form 8615)",
    boolean: false,
  },
  {
    factId: "parentHasPreferentialIncome",
    option: "--parent-has-gains",
    key: "parentHasGains",
    group: "Filing & family:",
    help: "parent has capital gains/qualified dividends (Form 8615 refuses — worksheet not modeled)",
    boolean: true,
  },
  {
    factId: "parentHasPreferentialIncome",
    option: "--parent-no-gains",
    key: "parentNoGains",
    group: "Filing & family:",
    help: "parent has NO preferential-rate income",
    boolean: true,
    setValue: false,
  },
  {
    factId: "socialSecurityBenefits",
    option: "--social-security <dollars>",
    key: "socialSecurity",
    group: "Income:",
    help: "social security benefits received (SSA-1099 box 5, \u00a7 86)",
    boolean: false,
  },
  {
    factId: "taxableIraDistributions",
    option: "--ira-distributions <dollars>",
    key: "iraDistributions",
    group: "Income:",
    help: "taxable IRA distributions (1099-R)",
    boolean: false,
  },
  {
    factId: "taxablePensionsAndAnnuities",
    option: "--pensions <dollars>",
    key: "pensions",
    group: "Income:",
    help: "taxable pensions and annuities (1099-R box 2a)",
    boolean: false,
  },
  {
    factId: "unemploymentCompensation",
    option: "--unemployment <dollars>",
    key: "unemployment",
    group: "Income:",
    help: "unemployment compensation (\u00a7 85)",
    boolean: false,
  },
  {
    factId: "earlyDistributionSubjectToPenalty",
    option: "--early-distribution <dollars>",
    key: "earlyDistribution",
    group: "Income:",
    help: "early retirement distribution subject to the 10% \u00a7 72(t) tax",
    boolean: false,
  },
  {
    factId: "ira8606Basis",
    option: "--ira8606-basis <dollars>",
    key: "ira8606Basis",
    group: "Income:",
    help: "Form 8606 line 2 prior-years IRA basis, per individual (use with target us.federal.ira8606.taxable_amount)",
    boolean: false,
  },
  {
    factId: "ira8606NondeductibleContributions",
    option: "--ira8606-nondeductible <dollars>",
    key: "ira8606Nondeductible",
    group: "Income:",
    help: "Form 8606 line 1 nondeductible IRA contributions for the year",
    boolean: false,
  },
  {
    factId: "ira8606YearEndValue",
    option: "--ira8606-value <dollars>",
    key: "ira8606Value",
    group: "Income:",
    help: "Form 8606 line 6 Dec-31 value of ALL this individual's trad/SEP/SIMPLE IRAs + outstanding rollovers",
    boolean: false,
  },
  {
    factId: "ira8606Distributions",
    option: "--ira8606-distributions <dollars>",
    key: "ira8606Distributions",
    group: "Income:",
    help: "Form 8606 line 7 distributions (excluding rollovers, conversions, QCDs)",
    boolean: false,
  },
  {
    factId: "ira8606Conversions",
    option: "--ira8606-conversions <dollars>",
    key: "ira8606Conversions",
    group: "Income:",
    help: "Form 8606 line 8 net amount converted to Roth IRAs",
    boolean: false,
  },
  {
    factId: "amtIsoExerciseSpread",
    option: "--iso-spread <dollars>",
    key: "isoSpread",
    group: "Investor (AMT / QSBS):",
    help: "ISO exercise bargain element held past year-end (AMT, \u00a7 56(b)(3))",
    boolean: false,
  },
  {
    factId: "amtOtherPreferences",
    option: "--amt-preferences <dollars>",
    key: "amtPreferences",
    group: "Investor (AMT / QSBS):",
    help: "other Form 6251 adjustments/preferences (PAB interest, depreciation, ...)",
    boolean: false,
  },
  {
    factId: "federalTaxWithheld",
    option: "--withheld <dollars>",
    key: "withheld",
    group: "Payments & estimated tax:",
    help: "federal tax withheld so far — switches the answer to balance due / refund expected",
    boolean: false,
  },
  {
    factId: "isAtLeastAge25",
    option: "--age25plus",
    key: "age25plus",
    group: "Filing & family:",
    help: "taxpayer is at least 25 (childless EITC age floor)",
    boolean: true,
  },
  {
    factId: "spouseItemizes",
    option: "--spouse-itemizes",
    key: "spouseItemizes",
    group: "Filing & family:",
    help: "spouse itemizes on a separate return (MFS)",
    boolean: true,
  },
  {
    factId: "occupation",
    option: "--occupation <job>",
    key: "occupation",
    group: "Income:",
    help: 'tipped occupation (fuzzy-matched to the Treasury list), or "other"',
    boolean: false,
  },
  {
    factId: "tipsWereVoluntary",
    option: "--service-charges",
    key: "serviceCharges",
    group: "Income:",
    help: "tips were mandatory service charges (NOT voluntary) — disqualifies § 224",
    boolean: true,
    setValue: false,
  },
  {
    factId: "employerIsSSTB",
    option: "--sstb",
    key: "sstb",
    group: "Income:",
    help: "tips received from a specified service trade or business — disqualifies § 224",
    boolean: true,
  },
  {
    factId: "useFormulaMethod",
    option: "--formula",
    key: "formula",
    group: "Expert:",
    help: "exact § 1 formula instead of the Tax Table under $100k (analysis mode)",
    boolean: true,
  },
  {
    factId: "entityLegalForm",
    option: "--entity <form>",
    key: "entity",
    group: "Corporate & entity (Form 1120):",
    help: "business legal form: llc | corporation (classification determinations)",
    boolean: false,
  },
  {
    factId: "llcMemberCount",
    option: "--members <n>",
    key: "members",
    group: "Corporate & entity (Form 1120):",
    help: "number of LLC members",
    boolean: false,
  },
  {
    factId: "filedForm8832CorpElection",
    option: "--form-8832",
    key: "form8832",
    group: "Corporate & entity (Form 1120):",
    help: "entity elected corporate classification (Form 8832)",
    boolean: true,
  },
  {
    factId: "filedForm2553SElection",
    option: "--s-election",
    key: "sElection",
    group: "Corporate & entity (Form 1120):",
    help: "entity filed a timely S election (Form 2553)",
    boolean: true,
  },
  {
    factId: "sCorpShareholderCount",
    option: "--shareholders <n>",
    key: "shareholders",
    group: "Corporate & entity (Form 1120):",
    help: "shareholder count, families aggregated (§ 1361(b): max 100)",
    boolean: false,
  },
  {
    factId: "sCorpHasIneligibleShareholder",
    option: "--ineligible-shareholder",
    key: "ineligibleShareholder",
    group: "Corporate & entity (Form 1120):",
    help: "a shareholder is ineligible for S status (e.g. nonresident alien)",
    boolean: true,
  },
  {
    factId: "sCorpHasMultipleStockClasses",
    option: "--multiple-stock-classes",
    key: "multipleStockClasses",
    group: "Corporate & entity (Form 1120):",
    help: "more than one class of stock (disqualifies S status)",
    boolean: true,
  },
  {
    factId: "corpTaxableIncome",
    option: "--corp-taxable-income <dollars>",
    key: "corpTaxableIncome",
    group: "Corporate & entity (Form 1120):",
    help: "C corporation taxable income, Form 1120 line 30 (§ 11 flat 21%)",
    boolean: false,
  },
  {
    factId: "corpAvgAdjustedFinancialStatementIncome",
    option: "--corp-afsi <dollars>",
    key: "corpAfsi",
    group: "Corporate & entity (Form 1120):",
    help: "3-yr average adjusted financial statement income (over $1B refuses — CAMT)",
    boolean: false,
  },
  {
    factId: "corpGrossIncome",
    option: "--corp-gross-income <dollars>",
    key: "corpGrossIncome",
    group: "Corporate & entity (Form 1120):",
    help: "corporation's gross income, incl. dividends received",
    boolean: false,
  },
  {
    factId: "corpOrdinaryDeductions",
    option: "--corp-deductions <dollars>",
    key: "corpDeductions",
    group: "Corporate & entity (Form 1120):",
    help: "ordinary business deductions (not charitable/DRD/NOL)",
    boolean: false,
  },
  {
    factId: "corpCharitableContributions",
    option: "--corp-charity <dollars>",
    key: "corpCharity",
    group: "Corporate & entity (Form 1120):",
    help: "corporate charitable contributions (10% ceiling; 1% floor from 2026)",
    boolean: false,
  },
  {
    factId: "corpDividendsReceived",
    option: "--corp-dividends <dollars>",
    key: "corpDividends",
    group: "Corporate & entity (Form 1120):",
    help: "intercorporate dividends received (§ 243 DRD)",
    boolean: false,
  },
  {
    factId: "corpDrdOwnershipTier",
    option: "--corp-drd-tier <tier>",
    key: "corpDrdTier",
    group: "Corporate & entity (Form 1120):",
    help: "ownership of the payer: under-20 | 20-to-80 | 80-plus",
    boolean: false,
  },
  {
    factId: "corpEquipmentPurchases",
    option: "--corp-equipment <dollars>",
    key: "corpEquipment",
    group: "Corporate & entity (Form 1120):",
    help: "qualified property placed in service (§ 168(k) 100% bonus)",
    boolean: false,
  },
  {
    factId: "corpDomesticResearch",
    option: "--corp-domestic-rd <dollars>",
    key: "corpDomesticRd",
    group: "Corporate & entity (Form 1120):",
    help: "domestic R&E, expensed currently (§ 174A)",
    boolean: false,
  },
  {
    factId: "corpForeignResearch",
    option: "--corp-foreign-rd <dollars>",
    key: "corpForeignRd",
    group: "Corporate & entity (Form 1120):",
    help: "foreign R&E, 15-year amortization (§ 174)",
    boolean: false,
  },
  {
    factId: "corpBusinessInterestExpense",
    option: "--corp-interest <dollars>",
    key: "corpInterest",
    group: "Corporate & entity (Form 1120):",
    help: "business interest expense (§ 163(j) 30% ATI limit)",
    boolean: false,
  },
  {
    factId: "corpAvgGrossReceipts3yr",
    option: "--corp-gross-receipts <dollars>",
    key: "corpGrossReceipts",
    group: "Corporate & entity (Form 1120):",
    help: "3-yr average gross receipts (§ 448(c): $31M/$32M exemption)",
    boolean: false,
  },
  {
    factId: "qsbsGain",
    option: "--qsbs-gain <dollars>",
    key: "qsbsGain",
    group: "Investor (AMT / QSBS):",
    help: "gain on qualified small business stock (§ 1202)",
    boolean: false,
  },
  {
    factId: "qsbsHoldingPeriodYears",
    option: "--qsbs-years <n>",
    key: "qsbsYears",
    group: "Investor (AMT / QSBS):",
    help: "whole years the QSBS was held",
    boolean: false,
  },
  {
    factId: "qsbsAcquiredAfterJuly2025",
    option: "--qsbs-post-obbba",
    key: "qsbsPostObbba",
    group: "Investor (AMT / QSBS):",
    help: "stock acquired after July 4, 2025 (tiered 50/75/100% regime)",
    boolean: true,
  },
  {
    factId: "qsbsAcquiredAfterJuly2025",
    option: "--qsbs-pre-obbba",
    key: "qsbsPreObbba",
    group: "Investor (AMT / QSBS):",
    help: "stock acquired on or before July 4, 2025 ($10M, 100% at 5 years)",
    boolean: true,
    setValue: false,
  },
  {
    factId: "qsbsAcquiredAfterSept2010",
    option: "--qsbs-post-2010",
    key: "qsbsPost2010",
    group: "Investor (AMT / QSBS):",
    help: "pre-OBBBA stock acquired after September 27, 2010",
    boolean: true,
  },
  {
    factId: "corpNOLCarryforward",
    option: "--corp-nol <dollars>",
    key: "corpNol",
    group: "Corporate & entity (Form 1120):",
    help: "NOL carryforward available (§ 172, 80% limit)",
    boolean: false,
  },
  {
    factId: "corpFDDEI",
    option: "--corp-fddei <dollars>",
    key: "corpFddei",
    group: "Corporate & entity (Form 1120):",
    help: "FDII (2025) / FDDEI (2026+) for the § 250 deduction",
    boolean: false,
  },
  {
    factId: "corpNCTI",
    option: "--corp-ncti <dollars>",
    key: "corpNcti",
    group: "Corporate & entity (Form 1120):",
    help: "GILTI inclusion + § 78 gross-up (2025) / NCTI (2026+)",
    boolean: false,
  },
  {
    factId: "generalBusinessCredits",
    option: "--gbc <dollars>",
    key: "gbc",
    group: "Corporate & entity (Form 1120):",
    help: "current-year § 38(b) general business credits",
    boolean: false,
  },
  {
    factId: "corpSection179Cost",
    option: "--corp-179 <dollars>",
    key: "corp179",
    group: "Corporate & entity (Form 1120):",
    help: "§ 179-elected property cost (incl. qualified real property; no vehicles)",
    boolean: false,
  },
  {
    factId: "corpFiscalYearFiler",
    option: "--corp-fiscal-year",
    key: "corpFiscalYear",
    group: "Corporate & entity (Form 1120):",
    help: "corporation uses a fiscal/short taxable year (refuses — §§ 15/443)",
    boolean: true,
  },
  {
    factId: "corpIsCoveredCorporation",
    option: "--corp-listed",
    key: "corpListed",
    group: "Corporate & entity (Form 1120):",
    help: "domestic corporation with stock on an established market (§ 4501)",
    boolean: true,
  },
  {
    factId: "corpStockRepurchasedFMV",
    option: "--corp-buybacks <dollars>",
    key: "corpBuybacks",
    group: "Corporate & entity (Form 1120):",
    help: "FMV of own stock repurchased this year (§ 4501 1% excise)",
    boolean: false,
  },
  {
    factId: "corpStockIssuedFMV",
    option: "--corp-stock-issued <dollars>",
    key: "corpStockIssued",
    group: "Corporate & entity (Form 1120):",
    help: "FMV of stock issued this year (§ 4501(c)(3) netting)",
    boolean: false,
  },
  {
    factId: "corpSection245ADividends",
    option: "--corp-foreign-dividends <dollars>",
    key: "corpForeignDividends",
    group: "Corporate & entity (Form 1120):",
    help: "§ 245A-eligible foreign-sub dividends (100% DRD; attested conditions)",
    boolean: false,
  },
  {
    factId: "aggregateBusinessLoss",
    option: "--business-loss <dollars>",
    key: "businessLoss",
    group: "Business owner:",
    help: "net aggregate business loss, positive number (§ 461(l) target)",
    boolean: false,
  },
  {
    factId: "corpForeignTaxesGeneral",
    option: "--corp-foreign-taxes <dollars>",
    key: "corpForeignTaxes",
    group: "Corporate & entity (Form 1120):",
    help: "general-basket foreign taxes (\u00a7 904 limitation)",
    boolean: false,
  },
  {
    factId: "corpForeignTaxesNCTI",
    option: "--corp-ncti-foreign-taxes <dollars>",
    key: "corpNctiForeignTaxes",
    group: "Corporate & entity (Form 1120):",
    help: "CFC-basket foreign taxes (\u00a7 960(d): 80%/90% allowance)",
    boolean: false,
  },
  {
    factId: "corpCapitalGains",
    option: "--corp-capital-gains <dollars>",
    key: "corpCapitalGains",
    group: "Corporate & entity (Form 1120):",
    help: "corporate capital gains (\u00a7 1211(a))",
    boolean: false,
  },
  {
    factId: "corpCapitalLosses",
    option: "--corp-capital-losses <dollars>",
    key: "corpCapitalLosses",
    group: "Corporate & entity (Form 1120):",
    help: "corporate capital losses incl. carryovers used (gains-only offset)",
    boolean: false,
  },
  {
    factId: "corpPriorYearTax",
    option: "--corp-prior-tax <dollars>",
    key: "corpPriorTax",
    group: "Corporate & entity (Form 1120):",
    help: "prior-year corporate tax (§ 6655 safe harbor)",
    boolean: false,
  },
  {
    factId: "corpIsLargeCorporation",
    option: "--large-corporation",
    key: "largeCorporation",
    group: "Corporate & entity (Form 1120):",
    help: "$1M+ taxable income in any of the 3 preceding years (§ 6655(g)(2))",
    boolean: true,
  },
  {
    factId: "corpIsLargeCorporation",
    option: "--not-large-corporation",
    key: "notLargeCorporation",
    group: "Corporate & entity (Form 1120):",
    help: "NOT a § 6655(g)(2) large corporation",
    boolean: true,
    setValue: false,
  },
  {
    factId: "priorYearTax",
    option: "--prior-tax <dollars>",
    key: "priorTax",
    group: "Payments & estimated tax:",
    help: "total tax on last year's return (§ 6654 safe harbor)",
    boolean: false,
  },
  {
    factId: "priorYearAGI",
    option: "--prior-agi <dollars>",
    key: "priorAgi",
    group: "Payments & estimated tax:",
    help: "AGI on last year's return (110% prong over $150k)",
    boolean: false,
  },
];

/**
 * Facts intentionally WITHOUT inline flags (facts-file / MCP oriented) —
 * the completeness contract test consults this list.
 */
export const FLAG_EXEMPT_FACTS = new Set([
  "depRelationshipChild",
  "depAge",
  "depIsFullTimeStudent",
  "depPermanentlyDisabled",
  "depYoungerThanTaxpayer",
  "depLivedWithTaxpayerOverHalfYear",
  "depProvidedOwnSupportOverHalf",
  "depFilesJointReturn",
  "depRelationshipRelative",
  "depGrossIncome",
  "taxpayerProvidedOverHalfSupport",
  "depIsQualifyingChildOfAnother",
  "wagesThroughMar31",
  "wagesThroughMay31",
  "wagesThroughAug31",
  "seProfitThroughMar31",
  "seProfitThroughMay31",
  "seProfitThroughAug31",
  "corpDividendsPaid",
  "corpAccumulatedEandPStart",
  "corpReasonableNeedsRetention",
  "corpIsPersonalServiceCorp",
  "corpPHCIncome",
  "corpAdjustedOrdinaryGrossIncome",
  "corpOwnedByFiveOrFewer",
  "corpUndistributedPHCIncome",
  "corpForeignSourceIncomeGeneral",
  "corpBaseErosionTestMet",
  "corpBaseErosionTaxBenefits",
  "corpPortfolioDebtFinancedPercent",
  "corpFilesConsolidatedReturn",
  "corpTIThrough3Months",
  "corpTIThrough6Months",
  "corpTIThrough9Months",
  "sCorpHasAccumulatedEandP",
  "sCorpPassiveInvestmentIncome",
  "sCorpGrossReceipts",
  "sCorpNetPassiveIncome",
  "sCorpTaxableIncomeAsC",
  "sCorpRecognizedBuiltInGain",
  "hasMultipleSupportAgreement",
  "taxpayerProvidedOver10PercentSupport",
  "depDivorcedParentsRule",
  "taxpayerIsCustodialParent",
  "custodialParentReleasedClaim",
]);

// first flag per fact wins (a fact may have paired true/false flags, e.g.
// --covered-by-plan / --not-covered-by-plan — hints show the primary one)
const BY_FACT = new Map<string, FactFlag>();
for (const f of FACT_FLAGS) {
  if (!BY_FACT.has(f.factId)) BY_FACT.set(f.factId, f);
}

/** "--status <single|mfj|hoh>"-style hint for a fact id, if a flag exists. */
export function flagFor(factId: string): string | undefined {
  return BY_FACT.get(factId)?.option;
}

/** Assemble facts from parsed commander options, using the table. */
export function factsFromOptions(
  opts: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const f of FACT_FLAGS) {
    const v = opts[f.key];
    if (f.boolean) {
      if (v === true) out[f.factId] = f.setValue ?? true;
    } else if (v !== undefined) {
      let value = v;
      if (typeof v === "string") {
        if (f.factId === "filingStatus" || f.factId === "parentFilingStatus") {
          value = normalizeStatus(v);
        }
        if (f.factId === "occupation") {
          const match = matchOccupation(v);
          if ("slug" in match) value = match.slug;
          else {
            throw new FactValidationError(
              match.candidates.length
                ? `"${v}" matches several listed occupations: ${match.candidates.join(", ")} — pick one`
                : `"${v}" is not on the Treasury Tipped Occupation list — pass one of the listed slugs, or "other" if the job is not listed (run \`opentax facts\` for details)`,
            );
          }
        }
      }
      out[f.factId] = value;
    }
  }
  return out;
}
